feat: add record size
cssxsh/mirai-administrator pull request #6
Opened 2022-04-13 03:41 UTC by DumKing

增加单群消息记录条数，节制内存占用

2022-04-14 03:43 UTC, cssxsh requested changes

2022-04-14 03:43 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/plugin/data/AdminSetting.kt
> +    @ValueDescription("单群最大记录消息条数 (范围内消息可撤回)")
record_limit
联系人（群/好友/...）聊天记录上限，（用于消息撤销等操作）

这样描述比较好

2022-04-14 04:05 UTC, DumKing commented on src/main/kotlin/xyz/cssxsh/mirai/plugin/data/AdminSetting.kt
> +    @ValueDescription("单群最大记录消息条数 (范围内消息可撤回)")
👌 已修改

2022-04-16 12:30 UTC, cssxsh approved these changes

2022-04-16 12:31 UTC, merged