fix:recall QuoteReply msg
cssxsh/mirai-administrator pull request #9
Opened 2022-04-22 10:38 UTC by DumKing

1. 群内通过回复撤销消息时，会自动@人员，原有代码会一直撤销指定人消息
2. 缩小处理自动申请的时间范围（事件只会发送给owner,监听好友消息即可）
3. 更新文档

2022-04-22 23:08 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/plugin/MiraiAdministrator.kt
> +    internal suspend fun FriendMessageEvent.approve() {
这种应该单独开 pr，或者 reopn 旧的 pr

2022-04-23 03:03 UTC, cssxsh commented
回复消息 时的 @ 是客户端自动添加的，可以去掉的
不过考虑到用户使用的方便，这样改动也是可以的
建议修改一下 AdminRecallCommand 的文档，说明一下优先级的变动

2022-04-23 03:04 UTC, cssxsh requested changes
回复消息 时的 @ 是客户端自动添加的，可以去掉的
不过考虑到用户使用的方便，这样改动也是可以的
建议修改一下 AdminRecallCommand 的文档，说明一下优先级的变动

2022-04-23 04:04 UTC, DumKing commented on src/main/kotlin/xyz/cssxsh/mirai/plugin/MiraiAdministrator.kt
> +    internal suspend fun FriendMessageEvent.approve() {
如果是扩展到群聊的话只能扩展群员的加群申请，同时需要将申请消息同步到群内，权限方面可能要考虑有机器人联系人处理权限或群管理权限即可，申请处理方式只提供通过引用回复这一种即可，handler应该拆分，~~感觉此功能意义不是很大~~🤪

2022-04-23 05:30 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/mirai/plugin/MiraiAdministrator.kt
> +    internal suspend fun FriendMessageEvent.approve() {
> 如果是扩展到群聊的话只能扩展群员的加群申请，同时需要将申请消息同步到群内，权限方面可能要考虑有机器人联系人处理权限或群管理权限即可，申请处理方式只提供通过引用回复这一种即可，handler应该拆分开，~如果只是为了加群审批响应速度，感觉此功能意义不是很大，最终都取决于人的响应速度~🤪

先把这个更改回溯了，这方面问题单独再开 issue/pr

2022-04-23 06:02 UTC, closed without merging

2022-04-23 07:05 UTC, DumKing commented
@cssxsh 我发现目前改法还是有问题的，要让回复消息撤销时优先级最高，需要优先处理event不为空且event的引用消息不为空时再细化处理contact的各种情况。感觉还是保持现状吧